import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
sns.set_theme()

sns.set(context='talk', style='ticks')

st.set_page_config(
     page_title="Previsão de venda",
     page_icon=":$:",
     layout="wide",
)

st.write('# Análise exploratória da previsão de renda')

st.divider()

renda = pd.read_csv('/Users/marcioslewis/Library/Mobile Documents/com~apple~CloudDocs/EBAC - CIENCIAS DE DADOS/EBAC - CIENTISTA DE DADOS/PROJETOS/PROJETO 2/input/previsao_de_renda.csv')

st.write('## Tabela de dados')
st.write(renda)
st.divider()

st.write('## Entendimento dos dados - Univariada')

st.write('### Gráficos de distribuição e frequência')
fig, ax = plt.subplots(12, 1, figsize=(10,70))
sns.histplot(x='renda', data=renda, ax=ax[0]).set_title('Renda')
ax[0].tick_params(axis='x', rotation=45)
ax[0].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='sexo', data=renda, ax=ax[1]).set_title('Sexo')
ax[1].tick_params(axis='x', rotation=45)
ax[1].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='posse_de_veiculo', data=renda, ax=ax[2]).set_title('Posse de Veículo')
ax[2].tick_params(axis='x', rotation=45)
ax[2].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='posse_de_imovel', data=renda, ax=ax[3]).set_title('Posse de Imóvel')
ax[3].tick_params(axis='x', rotation=45)
ax[3].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='qtd_filhos', data=renda, ax=ax[4]).set_title('Quantidade de Filhos')
ax[4].tick_params(axis='x', rotation=45)
ax[4].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='tipo_renda', data=renda, ax=ax[5]).set_title('Tipo de Renda')
ax[5].tick_params(axis='x', rotation=45)
ax[5].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='educacao', data=renda, ax=ax[6]).set_title('Educação')
ax[6].tick_params(axis='x', rotation=45)
ax[6].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='estado_civil', data=renda, ax =ax[7]).set_title('Estado Civil')
ax[7].tick_params(axis='x', rotation=45)
ax[7].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='tipo_residencia', data=renda, ax=ax[8]).set_title('Tipo de Residencia')
ax[8].tick_params(axis='x', rotation=45)
ax[8].set(ylabel='Frequencia', xlabel=None)
sns.histplot(x='idade', data=renda, ax=ax[9]).set_title('Idade')
ax[9].tick_params(axis='x', rotation=45)
ax[9].set(ylabel='Frequencia', xlabel=None)
sns.histplot(x='tempo_emprego', data=renda, ax=ax[10]).set_title('Tempo de Emprego')
ax[10].tick_params(axis='x', rotation=45)
ax[10].set(ylabel='Frequencia', xlabel=None)
sns.countplot(x='qt_pessoas_residencia', data=renda, ax=ax[11]).set_title('Quantidade de Pessoas na Residencia')
ax[11].tick_params(axis='x', rotation=45)
ax[11].set(ylabel='Frequencia', xlabel=None)
plt.subplots_adjust(wspace=0.2, hspace=0.8)
sns.despine()
st.pyplot(plt)

st.write('### Insight:')
st.write('Nesta primeira análise podemos verificar como as variáveis que serão utilizadas na\
         base de dados estão distribuídas.')

st.divider()

st.write('## Entendimento dos dados - Bivariada')

st.write('### Gráficos da renda em função do tempo')

fig, ax = plt.subplots(12, 1, figsize=(10,70))
sns.lineplot(x='data_ref', y='renda', data=renda, ax=ax[0], errorbar=None).set_title('Renda')
ax[0].tick_params(axis='x', rotation=45)
ax[0].set(ylabel=None, xlabel=None)
ax[0].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[1], errorbar=None, hue='sexo').set_title('Sexo')
ax[1].tick_params(axis='x', rotation=45)
ax[1].set(ylabel=None, xlabel=None)
ax[1].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[2], errorbar=None, hue='posse_de_veiculo').set_title('Posse de Veículo')
ax[2].tick_params(axis='x', rotation=45)
ax[2].set(ylabel=None, xlabel=None)
ax[2].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[3], errorbar=None, hue='posse_de_imovel').set_title('Posse de Imóvel')
ax[3].tick_params(axis='x', rotation=45)
ax[3].set(ylabel=None, xlabel=None)
ax[3].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[4], errorbar=None, hue='qtd_filhos').set_title('Quantidade de Filhos')
ax[4].tick_params(axis='x', rotation=45)
ax[4].set(ylabel=None, xlabel=None)
ax[4].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[5], errorbar=None, hue='tipo_renda').set_title('Tipo de Renda')
ax[5].tick_params(axis='x', rotation=45)
ax[5].set(ylabel=None, xlabel=None)
ax[5].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[6], errorbar=None, hue='educacao').set_title('Educação')
ax[6].tick_params(axis='x', rotation=45)
ax[6].set(ylabel=None, xlabel=None)
ax[6].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax =ax[7], errorbar=None, hue='estado_civil').set_title('Estado Civil')
ax[7].tick_params(axis='x', rotation=45)
ax[7].set(ylabel=None, xlabel=None)
ax[7].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[8], errorbar=None, hue='tipo_residencia').set_title('Tipo de Residencia')
ax[8].tick_params(axis='x', rotation=45)
ax[8].set(ylabel=None, xlabel=None)
ax[8].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[9], errorbar=None, hue='idade').set_title('Idade')
ax[9].tick_params(axis='x', rotation=45)
ax[9].set(ylabel=None, xlabel=None)
ax[9].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[10], errorbar=None, hue='tempo_emprego').set_title('Tempo de Emprego')
ax[10].tick_params(axis='x', rotation=45)
ax[10].set(ylabel=None, xlabel=None)
ax[10].legend(loc='upper right')
sns.lineplot(x='data_ref',y='renda', data=renda, ax=ax[11], errorbar=None, hue='qt_pessoas_residencia').set_title('Quantidade de Pessoas na Residencia')
ax[11].tick_params(axis='x', rotation=45)
ax[11].set(ylabel=None, xlabel=None)
ax[11].legend(loc='upper right')
plt.subplots_adjust(wspace=0.2, hspace=0.8)
plt.legend(loc='upper right')
sns.despine()
st.pyplot(plt)

st.write('### Insight:')
st.write('Analisando como a renda varia em função do tempo de acordo com as dadas variáveis, pode-se perceber que:')
st.write('- A variável sexo explica bem o valor da renda, segundo o gráfico, durante o período analisado, os homens sempre ganharam mais que as mulheres.')
st.write('- A variável posse_de_veiculo explica, também explica bem o valor da renda, em geral clientes que possuem carro possuem uma renda maior.')
st.write('- A variável tipo_renda, mais especificamente sevidor público, possui uma renda mais elevada.')
st.write('- Nas demais variáveis, suas respectivas categorias variam muito no decorrer do tempo, mantendo um padrão mais complicado de se perceber.')